name: ci

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - run: brew install coreutils
        if: runner.os == 'macOS'
      - run: ./configure
      - run: make check
      - run: make sanitize

  alpine:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - run: apk add --no-cache build-base bash grep sed coreutils
      - run: ./configure
      - run: make check

  freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: pkg install -y gmake coreutils
          run: |
            ./configure
            gmake check
